### ISSUE TITLE
Add support for 'Zeux' compression

### ISSUE THREAD

**Issue by wallabyway** [petrbroz/forge-convert-utils#15]
Deux compression is this...
  https://github.com/zeux/meshoptimizer

This is an alternative option to Draco.

This compression has shown favorable file sizes for AEC models compared to Draco (see here: https://github.com/KhronosGroup/glTF/issues/1699#issuecomment-565499098)

Secondarily - the wasm file size appears smaller, and the decoder performance is currently faster.

**Comment by petrbroz** [comment]
Thanks, the results from gltfpack are impressive!

One thing I've been wondering about lately is: should we keep adding different post-processing modules (like `gltf-pipeline`, or `gltfpack` in this case) to `forge-convert-utils`, or should we leave it to the users of this library? I think the latter would make more sense, because:

- users of `forge-convert-utils` would not be restricted to specific libraries and versions that we bundle in; they could just take the gltf that we generate and post-process it with any tool/version they want
- leaving additional dependencies would make this library more reusable
  - I've recently learned that if you use native Node.js modules as dependencies (I assume that's what `gltfpack` is doing since meshoptimizer is a C++ library), it makes it really difficult to use your library in Electron apps; for example, after I added `sqlite` dependency to this library, I was no longer able to use it in the VSCode extension...

What do you think?

**Comment by petrbroz** [comment]
Btw. here's a new branch that illustrates the idea: https://github.com/petrbroz/forge-convert-utils/tree/experiment/separate-postproc. It removes all the post-proc dependencies, and instead provides examples of how you can integrate `forge-convert-utils` with other tools: https://github.com/petrbroz/forge-convert-utils/blob/experiment/separate-postproc/test/remote-svf-to-gltf.sh.

**Comment by wallabyway** [comment]
Agreed.  My hunch is for `separate-postproc` and use a script `remote-svf-to-gltf.sh`
It's too soon to pick a compression and optimize.  Better to remain agile.

**Comment by petrbroz** [comment]
I've merged https://github.com/petrbroz/forge-convert-utils/tree/experiment/separate-postproc to `develop`. The example shell script now post-processes the glTF using `gltfpack` if available: https://github.com/petrbroz/forge-convert-utils/blob/develop/test/remote-svf-to-gltf.sh#L41-L44.

I'm also adding an experimental [Docker image](https://hub.docker.com/repository/docker/petrbroz/forge-convert-utils) as a quick way to start experimenting with the different post-processing tools. If you run:

```bash
docker pull petrbroz/forge-convert-utils
docker run --rm -it petrbroz/forge-convert-utils /bin/bash
```

... you have `forge-convert-utils`, `gltf-pipeline`, and `gltfpack` all available at your disposal.
