### ISSUE TITLE
Need more detailed example for parseMeshes

### ISSUE THREAD

**Issue by leefsmp** [petrbroz/forge-convert-utils#25]
Hi Petr! I would be interested in determining the bounding box of a given Forge model without loading it in the viewer. 

So my first question is am I correct that I would need to iterate all the meshes of the model and compute the union bbox myself? Or there is a global bbox data available directly?

Then my second is would you be able to provide a slightly more detailed example of using `parseMeshes`. I am not sure how I should get the `buffer` passed as input of `parseMeshes`. I've got a URN and a token, what should be the workflow to parse meshes of the whole model? Would be fantastic. 

Thanks ;)

**Comment by petrbroz** [comment]
Hi Philippe :)

Regarding the first question, each model usually has the world bounds stored in its metadata:

<img width="762" alt="Screen Shot 2020-09-14 at 9 42 20 AM" src="https://user-images.githubusercontent.com/1470668/93057841-d34b8a00-f66e-11ea-9fa2-43e882d8f7c9.png">

One thing I'm not sure about is whether it's _guaranteed_ to always be there, so computing the bounds yourself from the fragment list data might be a safer choice.

Regarding the second question, as you can see in the [SvfReader](https://github.com/petrbroz/forge-convert-utils/blob/3a625d1335ff6739818c9afbcef9e2055577aa51/src/svf/reader.ts#L450-L457) implementation, the `parseMeshes` function is used to process individual "geometry pack files" (_0.pf_, _1.pf_, _2.pf_, ...). The [samples](https://github.com/petrbroz/forge-convert-utils/tree/develop/samples) folder includes various usage examples. For example, you could take the [remote-svf-to-gltf.js](https://github.com/petrbroz/forge-convert-utils/blob/develop/samples/remote-svf-to-gltf.js) script and modify it by passing an existing token to the `ModelDerivativeClient` class instead of passing in client ID/secret. Or you can simply use the [command-line tool](https://github.com/petrbroz/forge-convert-utils/blob/develop/bin/forge-convert.js) available in this repository which can already accept `FORGE_ACCESS_TOKEN` as an env. variable.

**Comment by leefsmp** [comment]
Thanks.
