### ISSUE TITLE
Get internal properties of node

### ISSUE THREAD

**Issue by johannesheesterman** [petrbroz/forge-convert-utils#35]
What is the reasoning for skipping the 'internal attributes' in the getProperties method of the PropDbReader?
https://github.com/petrbroz/forge-convert-utils/blob/b5ea5e6a9620a61ab73e64e3b70c1b77e2660555/src/common/propdb-reader.ts#L60

It would be very useful for me if I could directly access these properties.

**Comment by johannesheesterman** [comment]
I just realised I could just use:
`Array.from(propDbReader.enumerateProperties(node.dbid));`

**Comment by petrbroz** [comment]
Hi Johannes, I intentionally skipped the `__*__` properties because those are not the "typical properties" (i.e., not the properties you would see in the Properties dialog in Forge Viewer). Those properties are supposed to include type of information such as parent-child relationships between different objects in the scene.

If there are strong arguments to include these properties in the list, I'd be happy to remove the if-condition.
