### ISSUE TITLE
Texture Mapping & Materials issues

### ISSUE THREAD

**Issue by alitehami** [petrbroz/forge-convert-utils#37]
Hello @petrbroz,

First Thank you for this great utility.

I am having issues maintaining the texture mapping of the converted models.

Here is a sample model scenario for a demo of the issue 

The original model is a 3dm rhino model:
![image](https://user-images.githubusercontent.com/38655738/125230956-2e94ea00-e31d-11eb-9a13-a9381cd92a65.png)

**glTF Textured model with Box Texture Mapping (converted from Rhino3d to glTF):**
![image](https://user-images.githubusercontent.com/38655738/125238686-e8df1e00-e32a-11eb-92c4-feff051b12d1.png)

Checker map of the above:
![image](https://user-images.githubusercontent.com/38655738/125238722-f4cae000-e32a-11eb-902a-de854a4ba903.png)

**3dm > translated to svf:**
if I convert the model with the forge-convert-utils from the svf version (converted via BIM360 upload) > the texture images get dropped, and the texture mapping scale seems to be getting changed:

No texture mapping once converted to glTF:
![image](https://user-images.githubusercontent.com/38655738/125231774-bc250980-e31e-11eb-9e4d-b571121a1965.png)

and the Material Name gets lost too:
![image](https://user-images.githubusercontent.com/38655738/125231611-710af680-e31e-11eb-9fc1-83821b10b57a.png)

**note:** 
- I do have the skip-uvs writer-options set to false.

attached are the rhino model, rhino-converted glTF model, and the forge-converted glTF model:
[Box_Texture Mapping_forge-convert-utils_millimeter.zip](https://github.com/petrbroz/forge-convert-utils/files/6798909/Box_Texture.Mapping_forge-convert-utils_millimeter.zip)

**Comment by petrbroz** [comment]
Thanks Ali! I just tried running the 3DM file through the Forge Model Derivative service, and it seems that the textures and UV coords are already dropped during the conversion into SVF:

<img width="646" alt="Screen Shot 2021-07-19 at 4 31 32 PM" src="https://user-images.githubusercontent.com/1470668/126178087-fa29ea7e-7653-42ec-916e-1212799d8000.png">

So I'm afraid there's not much I can do on the SVF-to-glTF side :/

Since it's looking like an issue with the Model Derivative service's support for Rhino files, I'd suggest that you send an official bug report to `forge (dot) help (at) autodesk (dot) com` (including the sample 3DM file if possible).

**Comment by alitehami** [comment]
Thanks for your reply @petrbroz , much appreciate you testing the files. I've sent an email reporting the bug.
