### ISSUE TITLE
SVF2 support

### ISSUE THREAD

**Issue by geirbi** [petrbroz/forge-convert-utils#39]
Hello,
Is there a way to use this to convert SVF2 derivatives? Or do you have any plans to add support for it?
I know there's some code for converting OTG, but I have not been able to use it for SVF2, and according to [this comment](https://github.com/petrbroz/vscode-forge-tools/issues/51#issuecomment-853870052) it needs more work.

Anyway, thanks for a nice tool!

**Comment by petrbroz** [comment]
Hi there, thanks! You're right - at the moment this library only has an experimental support for the OTG format (which is kind of like SVF2 but not entirely). I am thinking about adding SVF2 support at some point but cannot give any estimate on when that would happen.

In the meantime, let me track this as a feature request so that other people can comment/vote here as well.
