### ISSUE TITLE
ECONNRESET error when transferring SVF files from Forge services

### ISSUE THREAD

**Issue by wallabyway** [petrbroz/forge-convert-utils#48]
Getting a random ECONNRESET errors when download SVF resources from BIM360, when using Azure step function...

Is this a concurrency issue, or rate-limit error, or apogee error ?

![downloading-error](https://user-images.githubusercontent.com/440241/153963118-3cf0766a-9dc5-4308-b7aa-386c38aede76.JPG)

**Comment by petrbroz** [comment]
Just to make sure I understand this correctly: a customer is using `forge-convert-utils` in an Azure Function, trying to download SVF assets from Forge, and they're getting this `ECONNRESET` error when doing so?

If that's the case, I'd suggest getting more information about the specific Azure Function pricing plan, runtime version, and instrumenting the code with some more logs, incl. timestamps. And is the single function trying to download all the SVF assets, or just a subset of them? The reason I'm asking is, in certain cases the default timeout for Azure Functions can be as low as 5min: https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale#timeout.

**Comment by wallabyway** [comment]
@petrbroz - I believe you noticed this problem with Azure functions and separated the SVF download part, from the convert part.  And then used Azure Queue's to handle job tasks.
That seemed to be the workaround.  @petrbroz, perhaps you can share some of your code ?

**Comment by petrbroz** [comment]
I haven't shared the source code of that project intentionally because it includes some proprietary stuff and hacks (e.g., the gltf-to-usdz conversion is handled by making another HTTP request to a separate Heroku service running a custom Docker container...) so people wouldn't be able to reuse it anyways.

But I can at least share the architecture diagram, for inspiration:

![azure-setup](https://user-images.githubusercontent.com/1470668/154660550-c5b42cbe-a4f4-4acc-8c00-11e8910d7597.png)

**Comment by petrbroz** [comment]
It turns out that this issue was on the Azure Function side after all, so let me close this issue.

**Comment by camerongibbs-eic** [comment]
@petrbroz 
![image](https://user-images.githubusercontent.com/48618395/155037407-c6daaddc-a05e-40b5-b47c-c9cdbfd7a941.png)
function timeout is configured to 1 hour.
The function is hitting the ECONNRESET well before timeout, during the period where forge-convert-utils is printing the 'Reading meshpack #.. Reading materials' messages. 

We have a similar architecture where an https triggered function app puts a job to a queue. 
Then we have a queue triggered function app servicing the queue with a scale out of up to 10. It runs forge-convert-utils, giving the the urn and token so that it can do the download and conversion.
The problem seems to occur during periods of high scale out when there are a lot of messages posted to the queue close together so the queue triggered app scales out.

**Comment by petrbroz** [comment]
Thanks Cameron. How about separating the SVF download from the actual conversion? If you download the SVF using a separate Azure Function (and perhaps even using a custom code that could handle the ECONNRESET errors better), you could then use `forge-convert-utils` to translate a local folder with the SVF data instead.

**Comment by camerongibbs-eic** [comment]
@petrbroz thanks, we'll look into separating the download and conversion into separate stages when we get through the items on our roadmap. If you want to share the download code that would be appreciated, though I see it's a fairly easy to do step using the modelDerivativeClient.
