### ISSUE TITLE
Bounds offset

### ISSUE THREAD

**Issue by haydenjameslee** [petrbroz/forge-convert-utils#8]
https://github.com/petrbroz/forge-convert-utils/blob/630b8a6aa34415a071a5830991fc9adff7e68546/src/svf/fragments.ts#L23

Any word on finding the bbox offset? Might be helpful for us soon.

**Comment by petrbroz** [comment]
Let me take a look at that :+1:

**Comment by petrbroz** [comment]
Btw. about a month ago, I started computing the individual bounding boxes manually (due to some warnings generated by the glTF validator):

https://github.com/petrbroz/forge-convert-utils/blob/09701c4a37791f0968eda8cf91cc2ec8c1473da6/src/gltf/writer.ts#L383

Would that work for you guys, or do you need the original bounding boxes and their offsets for other purposes?

**Comment by haydenjameslee** [comment]
We're currently computing the bounds ourselves, but it would be ideal if we didn't have to download the entire geometry just to get the bounds. (we're not using this repo either btw, but we're using similar parsing code in another project).

**Comment by petrbroz** [comment]
Fair enough. I'm on it.

**Comment by petrbroz** [comment]
Looking at the LMV source code, it seems that the bbox logic is pretty straightforward. Basically, for SVF fragments in version 4 and above, all bounding boxes don't include their fragment's translation (to avoid precision loss issues). So in order to reconstruct the bboxes properly, you just have to add the translation back. I've updated the fragment parsing to follow that:

https://github.com/petrbroz/forge-convert-utils/blob/develop/src/svf/fragments.ts#L23-L34

**Comment by haydenjameslee** [comment]
thanks! appreciate it
